### ISSUE TITLE
System that listens to a folder and sends new files to a server

### ISSUE THREAD

**Issue by Nuottajarvi** [Urauth/Virtual-Campus-Art#1]
- Can be done with any programming language of choice
- Must listen to a folder
- When new file appears to folder reads it
- Posts it to a server using some type of file transfer protocol

**Comment by HerrGertrud** [comment]
The system is ready for testing. A frontend counterpart is needed if I am not entirely incorrect. So I'll just close it up and it can be reopened later, if necessary.
